config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :users
  resources :action_lists
  post 'logtask' => 'log_actions#log_task'

  root 'home#index'

end

app/models/action_list.rb
class ActionList < ActiveRecord::Base
	has_many :log_actions
	has_many :users, :through => :log_actions
	validates :name, presence: true
end

app/models/analyse_action.rb
class AnalyseAction < ActiveRecord::Base
	default_scope -> { order(:action_name1, :action_name2) }
end

app/models/log_action.rb
class LogAction < ActiveRecord::Base
  belongs_to :user
  belongs_to :action_list
  default_scope -> { order(created_at: :desc) }
  validates :action_list, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :log_actions
	has_many :action_lists, :through => :log_actions
	validates :name, presence: true
end

app/controllers/action_lists_controller.rb
class ActionListsController < ApplicationController
  before_action :set_action_list, only: [:show, :edit, :update, :destroy]

  # GET /action_lists
  # GET /action_lists.json
  def index
    @action_lists = ActionList.all
  end

  # GET /action_lists/1
  # GET /action_lists/1.json
  def show
    @probabilities=extract_action_info(@action_list.name)
  end

  # GET /action_lists/new
  def new
    @action_list = ActionList.new
  end

  # GET /action_lists/1/edit
  def edit
  end

  # POST /action_lists
  # POST /action_lists.json
  def create
    @action_list = ActionList.new(action_list_params)

    respond_to do |format|
      if @action_list.save
        format.html { redirect_to @action_list, notice: 'Action list was successfully created.' }
        format.json { render :show, status: :created, location: @action_list }
        # @analyse_action = AnalyseAction.new
        # debugger
        # @analyse_action.add_analyse(@action_list.name)
        add_analyse(@action_list.name)
        redirect_to action: "index" and return
      else
        format.html { render :new }
        format.json { render json: @action_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_lists/1
  # PATCH/PUT /action_lists/1.json
  def update
    respond_to do |format|
      if @action_list.update(action_list_params)
        format.html { redirect_to @action_list, notice: 'Action list was successfully updated.' }
        format.json { render :show, status: :ok, location: @action_list }
      else
        format.html { render :edit }
        format.json { render json: @action_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_lists/1
  # DELETE /action_lists/1.json
  def destroy
    @action_list.destroy
    respond_to do |format|
      format.html { redirect_to action_lists_url, notice: 'Action list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_list
      @action_list = ActionList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_list_params
      params.require(:action_list).permit(:name, :description)
    end
end

app/controllers/analyse_actions_controller.rb
class AnalyseActionsController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AnalyseActionsHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/log_actions_controller.rb
class LogActionsController < ApplicationController

	def log_task
		@action = LogAction.new
		@user = User.find_by_name(params[:name])
		@action.user_id = @user.id
		@action.action_list_id = params[@user.id.to_s][:action_list_id]
		if @action.save
		  update_analyse(@action)
	      flash[:success] = "Task added successfully"
	      redirect_to @user
    	else
      	  redirect_to :back
    	end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/action_lists_helper.rb
module ActionListsHelper
end

app/helpers/analyse_actions_helper.rb
module AnalyseActionsHelper

	def add_analyse(action_name)
		actions= ActionList.pluck(:name)
		actions.delete(action_name)
		actions.each do |action_name2|
			@action_analyse = AnalyseAction.new
			@action_analyse.update_attributes(:action_name1 => action_name, :action_name2 => action_name2, :immediate => 0, :weekly => 0, :monthly => 0, :yearly => 0, :lifetime => 0)
			@action_analyse.save

			@action_analyse1 = AnalyseAction.new
			@action_analyse1.update_attributes(:action_name1 => action_name2, :action_name2 => action_name, :immediate => 0, :weekly => 0, :monthly => 0, :yearly => 0, :lifetime => 0)
			@action_analyse1.save			
		end
	end


	def update_analyse(action)
		created_at = action.created_at
		new_action = ActionList.find(action.action_list_id)
		log_actions = LogAction.where("user_id = ? AND action_list_id != ?", action.user_id, action.action_list_id)
		log_actions.each do |log_action|
			difference = calculate_frequency(created_at, log_action.created_at)
			# analyse_action = AnalyseAction.where("action_name1 = ? AND action_name2 = ?", new_action.name, ActionList.find(log_action.action_list_id).name)
			analyse_action = AnalyseAction.find_by_action_name1_and_action_name2(ActionList.find(log_action.action_list_id).name, new_action.name)
			if difference >= 0 && difference < 1
				analyse_action.immediate += 1
			elsif difference >= 1 && difference <= 7
				analyse_action.weekly += 1
			elsif difference > 7 && difference <= 30
				analyse_action.monthly += 1
			elsif difference > 30 && difference <= 365
				analyse_action.yearly += 1
			else
				analyse_action.lifetime += 1
			end
			analyse_action.save
		end
	end

	def calculate_frequency(created_at_new_action, created_at_old_actions)
		TimeDifference.between(created_at_new_action, created_at_old_actions).in_days
	end


	def extract_action_info(action_name)
		action_output = AnalyseAction.where("action_name1 = ?", action_name).pluck(:action_name2, :immediate, :weekly, :monthly, :yearly, :lifetime)
		sum_of_actions = action_output.transpose.map {|a| a.inject(:+)}
		new_arr = []

		action_output.each do |x|
		  z=[]
		  x.each_with_index do |y, i|
		  	if i == 0
		  	   z[i] = y[i]
		  	elsif sum_of_actions[i] > 0
		  	   z[i] = (((y.to_f)/(sum_of_actions[i].to_f)) * 100) 
		  	else
		  	   z[i] = 0.0
		  	end	  	
		  end
		  new_arr << z
		end
		new_arr
		# new_arr.transpose
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/log_actions_helper.rb
module LogActionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/action_lists/_form.html.erb
<%= form_for(@action_list) do |f| %>
  <% if @action_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_list.errors.count, "error") %> prohibited this action_list from being saved:</h2>

      <ul>
      <% @action_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_lists/edit.html.erb
<h1>Editing Action List</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_list %> |
<%= link_to 'Back', action_lists_path %>

app/views/action_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Select action name from below to analyse action</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_lists.each do |action_list| %>
      <tr>
        <td><%= action_list.name %></td>
        <td><%= action_list.description %></td>
        <td><%= link_to 'Analyse Action |', action_list %></td>
        <td><%= link_to 'Edit Action |', edit_action_list_path(action_list) %></td>
        <td><%= link_to 'Destroy', action_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action list', new_action_list_path %>

app/views/action_lists/new.html.erb
<h1>New Action List</h1>

<%= render 'form' %>

<%= link_to 'Back', action_lists_path %>

app/views/action_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Below table shows probability of associated actions </h1>
<p>
  <strong>Action Name:</strong>
  <%= @action_list.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_list.description %>
</p>


<table style="width:100%">
  <tr>
    <th>Action Name</th>
    <th>Immideate Probability</th> 
    <th>Weekly Probability</th>
    <th>Monthly Probability</th>
    <th>Yearly Probability</th>
    <th>Lifetime Probability</th>
  </tr>
  <% @probabilities.each do |x| %>
  
  <tr>
    <% x.each_with_index do |y, i| %>
    <td><%= y %></td>
    <%end%>
  </tr>
  
  <%end%>
</table> 


<%= link_to 'Edit', edit_action_list_path(@action_list) %> |
<%= link_to 'Back', action_lists_path %>

app/views/home/index.html.erb
<h1>Action Tracker</h1>

<ul>
<li><%= link_to 'Log Action', users_path %></li>
<li><%= link_to 'Analyse Action', action_lists_path %></li>
<li><%= link_to 'Add Action', new_action_list_path %> </li>
<li><%= link_to 'Add User', new_user_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActionTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

 <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Click on below users to log action for</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Log Action |', user %></td>
        <td><%= link_to 'Edit |', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h2> Select action for this user </h2>
<div>
<%= form_tag(controller: "log_actions", action: "log_task") do %>

  <%= label_tag(:name, 'User name') %>
  <%= text_field_tag(:name, @user.name, :readonly => true) %><br/>
  
  <%= label_tag :action_list, 'Select Action' %>
  <%= collection_select(@user.id, :action_list_id, ActionList.all, :id, :name, :include_blank => "Please select action") %><br/>

  <%= submit_tag("Submit") %>
<% end %>
</div>
<br/>
<p>
  <strong> Below are logged in task for the user:</strong>
  <%= @user.name %>
</p>
<ul>
  <% @user.action_lists.each do |action| %>
   <li><span>Task Name: <%= action.name %></span></li>
  <%end%>
</ul>

<br/>
<%= link_to 'Edit User', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>